eureka and cs

diff --git a/.bluemix/wfd-config-server-ic-pipeline.yml b/.bluemix/wfd-config-server-ic-pipeline.yml
--- a/.bluemix/wfd-config-server-ic-pipeline.yml
+++ b/.bluemix/wfd-config-server-ic-pipeline.yml
@@ -118,7 +118,7 @@ stages:
         # Copy any artifacts that will be needed for deployment and testing to $WORKSPACE    #
         ######################################################################################
         echo "IMAGE_NAME=${FULL_REPOSITORY_NAME}" >> $ARCHIVE_DIR/build.properties
-- name: Deploy Container Group
+- name: Deploy
   inputs:
   - type: job
     stage: Build Docker Image
@@ -146,10 +146,7 @@ stages:
     value: ${CONTAINER_SIZE}
     type: text
   - name: IGNORE_MAPPING_ROUTE
-    value: 'true'
-    type: text
-  - name: CONFIG_SERVER_UPS
-    value: ${CONFIG_SERVER_UPS}
+    value: ${IGNORE_MAPPING_ROUTE}
     type: text
   - name: BRIDGE_APP
     value: ${BRIDGE_APP}
@@ -172,8 +169,47 @@ stages:
   - name: PORT
     value: ${PORT}
     type: text
+  - name: ROUTE_DOMAIN
+    value: ${ROUTE_DOMAIN}
+    type: text
+  - name: ROUTE_HOSTNAME
+    value: ${ROUTE_HOSTNAME}
+    type: text
+  - name: TEST_RESULT_FOR_AD
+    value: ${TEST_RESULT_FOR_AD}
+    type: text
+  - name: GROUP_SIZE
+    value: ${GROUP_SIZE}
+    type: text
+  - name: DEBUG
+    value: ${DEBUG}
+    type: text
+  - name: GIT_HOME
+    value: ${GIT_HOME}
+    type: text
+  - name: RAMPDOWN_DURATION
+    value: ${RAMPDOWN_DURATION}
+    type: text
+  - name: RAMPUP_DURATION
+    value: ${RAMPUP_DURATION}
+    type: text
+  - name: SERVICE_DISCOVERY_UPS
+    value: ${SERVICE_DISCOVERY_UPS}
+    type: text
+  - name: CS_CONTAINER_GR_ID
+    value: null
+    type: text
+  - name: CS_CONTAINER_GR_IP
+    value: null
+    type: text
+  - name: UNIQUE_IDENTIFIER
+    value: ${UNIQUE_IDENTIFIER}
+    type: text
+  - name: CONFIG_SERVER_UPS
+    value: ${CONFIG_SERVER_UPS}
+    type: text
   jobs:
-  - name: Deploy
+  - name: Deploy Container Group
     type: deployer
     extension_id: ibm.devops.services.pipeline.docker.deploy.ice
     target:
@@ -185,29 +221,23 @@ stages:
     CONTAINER_NAME: ${NAME}
     COMMAND: |-
       #!/bin/bash
+
+      # -------------- #
+      # Set debug mode #
+      # -------------- #
+      if [[ -n ${DEBUG} ]]; then set -x ; fi
+
+      echo -e "${label_color}# ------------------------------- #${no_color}"
+      echo -e "${label_color}# [BEGIN]: Deploy Container Group #${no_color}"
+      echo -e "${label_color}# ------------------------------- #${no_color}"
+
        # The following are some example deployment scripts.  Use these as is or fork them and include your updates here:
        echo -e "${label_color}Starting deployment script${no_color}"
        # To view/fork this script goto: https://github.com/Osthanes/deployscripts
        # git_retry will retry git calls to prevent pipeline failure on temporary github problems
        # the code can be found in git_util.sh at https://github.com/Osthanes/container_deployer
        git_retry clone https://github.com/Osthanes/deployscripts.git deployscripts
-       # You can deploy your Image as either a single Container or as a Container
-       # Group.  A Container Group deploys a number of containers to enhance
-       # scalability or reliability.  By default we will deploy as a single
-       # container.  To switch to a group deploy, comment out the line below
-       # containing deploycontainer.sh and uncomment the line for deploygroup.sh
-       # Deploy with containers:
-       # Optional environment properties (can be set directly in this script, or defined as environment properties):
-       #      NAME              Value         Description
-       #   =============      =========     ==============
-       #   BIND_TO             String       Specify a Bluemix application name that whose bound services you wish to make available to the container.  By default this is not set.
-       #   CONTAINER_SIZE      String       Specify container size: pico (64), nano (128), micro (256), tiny (512), small (1024), medium (2048),
-       #                                                            large (4096), x-large (8192), 2x-large (16384).
-       #                                    Default is micro (256).
-       #   CONCURRENT_VERSIONS Number       Number of versions of this container to leave active.
-       #                                    Default is 1
-       #
-       # /bin/bash deployscripts/deploycontainer.sh
+
        # Deploy Container Group:
        # Optional environment properties (can be set directly in this script, or defined as environment properties):
        #      NAME              Value         Description
@@ -243,62 +273,160 @@ stages:
            exit $RESULT
        fi
        echo -e "${green}Execution complete${no_label}"
-  - name: Deploy CUPS
+
+       export NAME="${CONTAINER_NAME}_${BUILD_NUMBER}"
+       echo "Value of NAME: ${NAME}"
+
+       echo -e "${label_color}# ----------------------------- #${no_color}"
+       echo -e "${label_color}# [END]: Deploy Container Group #${no_color}"
+       echo -e "${label_color}# ----------------------------- #${no_color}"
+
+       echo -e "${label_color}# -------------------- #${no_color}"
+       echo -e "${label_color}# [BEGIN]: Deploy CUPS #${no_color}"
+       echo -e "${label_color}# -------------------- #${no_color}"
+
+       echo "Begining Config Server CUPS deployment"
+
+       CS_CONTAINER_GR_ID=`cf ic group list | grep $NAME | sed 's/ .*$//g'`
+       CS_CONTAINER_GR_IP=cf ic group inspect $CS_CONTAINER_GR_ID | grep private_ip_address | sed 's/.*: "\(.*\)".*$/\1/g'`
+
+       echo "Config Server container group ID: $CS_CONTAINER_GR_ID"
+       echo "Config Server container group IP: $CS_CONTAINER_GR_IP"
+
+       if [ -z "$(cf services | grep ${CONFIG_SERVER_UPS})" ]; then
+         cf create-user-provided-service ${CONFIG_SERVER_UPS} -p "{\"uri\": \"http://$CS_CONTAINER_GR_IP:${PORT}/\"}"
+       else
+         cf update-user-provided-service ${CONFIG_SERVER_UPS} -p "{\"uri\": \"http://$CS_CONTAINER_GR_IP:${PORT}/\"}";
+       fi
+
+       echo -e "${label_color}# ------------------ #${no_color}"
+       echo -e "${label_color}# [END]: Deploy CUPS #${no_color}"
+       echo -e "${label_color}# ------------------ #${no_color}"
+
+       echo -e "${label_color}# -------------------------- #${no_color}"
+       echo -e "${label_color}# [BEGIN]: Deploy Bridge App #${no_color}"
+       echo -e "${label_color}# -------------------------- #${no_color}"
+
+       if [ -z "$(cf apps | grep ${BRIDGE_APP})" ]; then
+          echo "[ERROR]: The container bridge app does not exists."
+          echo "[ERROR]: Please, check the Eureka pipeline."
+ 	        exit 1
+       else
+          echo "[OK]: Bridge App exists"
+ 	        if [ -z "$(cf services | grep ${CONFIG_SERVER_UPS})" ]; then
+            echo "[ERROR]: The Config Server CUPS service has not been found."
+            echo "[ERROR]: Please, check previous step in this pipeline."
+            exit 1
+          else
+            echo "[OK]: Config Server CUPS exists"
+            if [ -z "$(cf services | grep ${CONFIG_SERVER_UPS} | grep ${BRIDGE_APP})" ]; then
+ 		           cf bind-service ${BRIDGE_APP} ${CONFIG_SERVER_UPS}
+               echo "[OK]: Config Server and Bridge App bound"
+            else
+               echo "[OK]: Config Server and Bridge App were already bound"
+ 	          fi
+          fi
+       fi
+
+       echo -e "${label_color}# ------------------------ #${no_color}"
+       echo -e "${label_color}# [END]: Deploy Bridge App #${no_color}"
+       echo -e "${label_color}# ------------------------ #${no_color}"
+
+       echo -e "${label_color}# ------------------------------- #${no_color}"
+       echo -e "${label_color}# [BEGIN]: Updating microservices #${no_color}"
+       echo -e "${label_color}# ------------------------------- #${no_color}"
+
+       for MICROSERVICE in `cf ic group list | grep ${UNIQUE_IDENTIFIER} | grep -v eureka | sed 's/    .*$//g' | sed 's/^.*  //g'`
+       do
+         echo "[INFO]: Updating Eureka url for microservice: $MICROSERVICE"
+
+         MICROSERVICE_CONTAINER_GR_ID=`cf ic group list | grep $MICROSERVICE | sed 's/ .*$//g'`
+         echo "[INFO]: $MICROSERVICE container group id: $MICROSERVICE_CONTAINER_GR_ID"
+
+         OLD_VCAP_SERVICES=`cf ic group inspect $MICROSERVICE_CONTAINER_GR_ID | grep 'VCAP_SERVICES=' | sed 's/^.*VCAP_SERVICES=\(.*\)",.*$/\1/g'`
+         echo "[INFO]:$MICROSERVICE old VCAP Services: $OLD_VCAP_SERVICES"
+
+         NEW_VCAP_SERVICES=`echo $OLD_VCAP_SERVICES | sed 's@\(^.*eureka.*\)http://.*:$PORT@\1http://$CS_CONTAINER_GR_IP:$PORT@g'
+         echo "[INFO]:$MICROSERVICE new VCAP Services: $NEW_VCAP_SERVICES"
+
+         cf ic group update -e "VCAP_SERVICES=$NEW_VCAP_SERVICES" $MICROSERVICE
+       done
+
+       echo -e "${label_color}# ----------------------------- #${no_color}"
+       echo -e "${label_color}# [END]: Updating microservices #${no_color}"
+       echo -e "${label_color}# ----------------------------- #${no_color}"
+       
+  - name: Active Deploy - Begin
     type: deployer
-    extension_id: ibm.devops.services.pipeline.docker.deploy.ice
+    extension_id: ibm.devops.services.pipeline.devops.ad_start
     target:
       region_id: ${REGION}
       organization: ${ORG}
       space: ${SPACE}
-    DEPLOY_TYPE: simple
-    PORT: ${PORT}
-    CONTAINER_NAME: ${CONFIG_SERVER_UPS}
+    DEPLOYMENT_METHOD: Red Black
+    RAMPDOWN_DURATION: ${RAMPDOWN_DURATION}
+    RAMPUP_DURATION: ${RAMPUP_DURATION}
     COMMAND: |-
-      #!/bin/bash -x
+      #!/bin/bash
+      #
+      # The following code uses the Active Deploy service to update your new application with zero downtime.
+      # The code used is available at https://github.com/Osthanes/update_service
+      # and https://github.com/Osthanes/activedeploy_common.
+      #
+      # For details about how to set up the Active Deploy extension for the Delivery Pipeline, see
+      # https://console.ng.bluemix.net/docs/services/ActiveDeploy/updatingapps.html#adpipeline.
+      #
+      # Feel free to fork the code. After creating your fork, define the environment variable GIT_HOME to use the forked repositories with the
+      # format https://github.com/${GIT_HOME}/update_service and https://github.com/${GIT_HOME}/activedeploy_common.
+      #
+      # Make sure the following variables are defined as environment properties with no values:
+      # NAME: The name of your new application. This variable has to be exported in the first deploy job.
+      # TEST_RESULT_FOR_AD: Passes the results of the test phase to the Active Deploy - Complete job. Set this variable in the test job.
+      #
+      # The following variables may be defined as environment properties:
+      # GROUP_SIZE: The number of instances that are created during initial deployment. The default value is 1.
+      # CONCURRENT_VERSIONS: The number of application versions to keep at the end of deployment. The default value is 2.
+      # AD_INSTANCE_NAME: The name for Active Deploy Instance, if it does not yet exist. The default value is activedeploy-for-pipeline.
 
-      echo "Begining Config Server CUPS deployment"
-      echo "Container image name: $IMAGE_NAME"
-
-      CS_CONTAINER_ID=`cf ic ps | grep "$IMAGE_NAME" | sed 's/  *.*$//g'`
-      CS_IP_ADDRESS=`cf ic inspect $CS_CONTAINER_ID | grep IPAddress | sed 's/  *.*: "//g' | sed 's/",$//g' | uniq`
-
-      echo "Config Server container ID: $CS_CONTAINER_ID"
-      echo "Config Server container IP address: $CS_IP_ADDRESS"
-
-      if [ -z "$(cf services | grep ${CONFIG_SERVER_UPS})" ]; then
-        cf create-user-provided-service ${CONFIG_SERVER_UPS} -p "{\"uri\": \"http://$CS_IP_ADDRESS:${PORT}/\"}"
-      else
-        cf update-user-provided-service ${CONFIG_SERVER_UPS} -p "{\"uri\": \"http://$CS_IP_ADDRESS:${PORT}/\"}";
-      fi
-  - name: Deploy Bridge app
-    type: deployer
-    target:
-      region_id: ${REGION}
-      organization: ${ORG}
-      space: ${SPACE}
-      application: ${BRIDGE_APP}
+      source ${EXT_DIR}/git_util.sh
+      git_retry clone https://github.com/${GIT_HOME}/update_service.git activedeploy
+      activedeploy/activedeploy_step_1.sh
+  - name: Test
+    type: tester
+    fail_stage: false
     script: |-
       #!/bin/bash
-      echo "[BEGIN]: Bind to Bridge App"
+      # invoke tests here
 
-      if [ -z "$(cf apps | grep ${BRIDGE_APP})" ]; then
-        echo "[ERROR]: The container bridge app does not exists."
-	      echo "[ERROR]: Please, check the Eureka pipeline."
-	      exit 1
-      else
-        echo "[OK]: Bridge App exists"
-	      if [ -z "$(cf services | grep ${CONFIG_SERVER_UPS})" ]; then
-		      echo "[ERROR]: The Eureka CUPS service has not been found."
-		      echo "[ERROR]: Please, check previous step in this pipeline."
-          exit 1
-        else
-          echo "[OK]: Config Server CUPS exists"
-          if [ -z "$(cf services | grep ${CONFIG_SERVER_UPS} | grep ${BRIDGE_APP})" ]; then
-		        cf bind-service ${BRIDGE_APP} ${CONFIG_SERVER_UPS}
-		        echo "[OK]: Config Server and Bridge App bound"
-          else
-		        echo "[OK]: Config Server and Bridge App were already bound"
-	        fi
-        fi
-      fi
-      echo "[END]: Deploy Bridge App"
+      # -------------- #
+      # Set debug mode #
+      # -------------- #
+      if [[ -n ${DEBUG} ]]; then set -x ; fi
+
+      export TEST_RESULT_FOR_AD=0
+
+      echo "No test carried out"
+  - name: Active Deploy - Complete
+    type: deployer
+    extension_id: ibm.devops.services.pipeline.devops.ad_finish
+    target:
+      region_id: ${REGION}
+      organization: ${ORG}
+      space: ${SPACE}
+    COMMAND: |-
+      #!/bin/bash
+      #
+      # The following code uses the Active Deploy service to update your new application with zero downtime.
+      # The code used is available at https://github.com/Osthanes/update_service
+      # and https://github.com/Osthanes/activedeploy_common.
+      #
+      # For details about how to set up the Active Deploy extension for the Delivery Pipeline, see
+      # https://console.ng.bluemix.net/docs/services/ActiveDeploy/updatingapps.html#adpipeline.
+      #
+      # Feel free to fork the code. After creating your fork, define the environment variable GIT_HOME to use the forked repositories with the
+      # format https://github.com/${GIT_HOME}/update_service and https://github.com/${GIT_HOME}/activedeploy_common.
+      #
+
+      source ${EXT_DIR}/git_util.sh
+      git_retry clone https://github.com/${GIT_HOME}/update_service.git activedeploy
+      activedeploy/activedeploy_step_2.sh
